import React from "react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import "tailwindcss/tailwind.css";

// import { moizaLogo } from "../../static/image/logo/index";

const inter = Inter({ subsets: ["latin"] });

const Main = () => {
  return (
    <div className="m-auto lg:w-1/4 w-screen h-screen items-center flex justify-center shadow-xl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-red-500 items-center m-1 flex justify-center flex-col">
        <div>
          {/* <Image
            src={moizaLogo}
            width={200}
            alt="Logo"
            className="m-auto mb-32"
          /> */}
          mainpage
        </div>
        {/*tailwindcss로 css 적용 했고, Link 태그 구글링 해보세요*/}
        <h1 className="text-center text-black hover:text-gray-500 text-xl rounded-md ">
          Read{" "}
          <Link href="/pracTailwindcss/pracTailwindcssConponent">
            this page for TailWindCSS!
          </Link>
        </h1>
        {/*---------------------------------------------------------------------------------------*/}
      </div>
    </div>
  );
};

export default Main;
