import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import "tailwindcss/tailwind.css";

import { moizaLogo } from "../static/index";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="m-auto lg:w-1/4 w-screen h-screen items-center flex justify-center shadow-xl">
      <Head>
        <title>Loding...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/moizaFavicon.png" />
      </Head>
      <div className="items-center m-1 flex justify-center flex-col">
        <div>
          <Image
            src={moizaLogo}
            width={200}
            alt="Logo"
            className="m-auto mb-32"
          />
        </div>
        {/*tailwindcss로 css 적용 했고, Link 태그 구글링 해보세요*/}
        <h1 className="text-center text-blue-500 hover:text-gray-500 text-xl rounded-md ">
          Read{" "}
          <Link href="/pracTailwindcss/pracTailwindcssConponent">
            this page for TailWindCSS!
          </Link>
        </h1>
        {/*---------------------------------------------------------------------------------------*/}
        {/*Loading page 링크입니다*/}
        <h1 className="text-center text-orange-600 hover:text-gray-500 text-xl rounded-md ">
          Read{" "}
          <Link href="/LoadingPage/Loading">
            this page for LoadingPage!
          </Link>
        </h1>
        {/*---------------------------------------------------------------------------------------*/}
      </div>
    </div>
  );
}
