import React from "react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import "tailwindcss/tailwind.css";

import { moizaLogo } from "../../static/index";

const inter = Inter({ subsets: ["latin"] });

const Loading = () => {
  return (
    <div className="m-auto lg:w-1/4 w-screen h-screen items-center flex justify-center shadow-xl">
      <Head>
        <title>Loding...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/moizaFavicon.png" />
      </Head>
      <div className="items-center m-1 flex justify-center flex-col">
        <div>
          <Image
            src={moizaLogo}
            width={200}
            alt="Logo"
            className="m-auto mb-8"
          />
        </div>
        <p className="m-auto mb-8">Loading...</p>
      </div>
    </div>
  );
};

export default Loading;
